---
title: "NaiveBayes_FRA.rmd"
author: "Prasanta Panja"
date: "3 December 2017"
output: html_document
---

##Importing Libraries

```{r setup, include=FALSE}
# install.packages("caTools")
# install.packages("DMwR")

library("xlsx")
library("car")
library("RColorBrewer")
library("dplyr")
library("DMwR")
library("caTools")
library("ROCR")
library("e1071")
library("ineq")
library("data.table")
```

## Settingup working directory and Reading training data

```{r}
setwd("C:/Users/Prasanta/Downloads/PGPBABI/FRA/GA")
train <- read.xlsx("training.xlsx",sheetName = "training")
```

## Training Data Preparation

```{r}
train1 <- train %>% filter(NumberOfDependents != 'NA')
train2 <- train %>% filter(NumberOfDependents == 'NA')

sd(as.numeric(as.character((train1$NumberOfDependents))))
mean(as.numeric(as.character((train1$NumberOfDependents))))
train2$NumberOfDependents <- ceiling(rnorm(142,.74,1.10))
train2$NumberOfDependents <- ifelse(train2$NumberOfDependents < 0,0,train2$NumberOfDependents)
train1$NumberOfDependents <- as.numeric(as.character(train1$NumberOfDependents))
train3 <- rbind(train1,train2)
bank <- train3
ncol(bank)

#check for missing values
table(is.na(bank))
colSums(is.na(bank))


# Outlier Treatment
quantile(bank$RevolvingUtilizationOfUnsecuredLines, c(0.05,0.1,0.2,0.3,0.4,0.50,0.6,0.7,0.8,0.9,0.95,0.99,1))

bank$RevolvingUtilizationOfUnsecuredLines[which(bank$RevolvingUtilizationOfUnsecuredLines>=1)]<- 0.897

quantile(bank$DebtRatio, c(0.05,0.1,0.2,0.3,0.4,0.50,0.6,0.7,0.8,0.9,0.95,0.99,1))

quantile(bank$NumberOfOpenCreditLinesAndLoans, c(0.05,0.1,0.2,0.3,0.4,0.50,0.6,0.7,0.8,0.9,0.95,0.99,1))

bank$NumberOfDependents <- as.numeric(as.character(bank$NumberOfDependents))
quantile(bank$NumberOfDependents, c(0.05,0.1,0.2,0.3,0.4,0.50,0.6,0.7,0.8,0.9,0.95,0.99,1))

RFDF <- bank

## Response Rate
RFDF.dev <- RFDF
RFDF.dev$Target <- RFDF.dev$SeriousDlqin2yrs
RFDF.dev<- RFDF.dev[-c(1,2)]
```


## Test Data Preparation

```{r}
test <- read.xlsx("test.xlsx",sheetName = "test")
test1 <- test %>% filter(NumberOfDependents != 'NA')
test2 <- test %>% filter(NumberOfDependents == 'NA')

sd(as.numeric(as.character((test1$NumberOfDependents))))
mean(as.numeric(as.character((test1$NumberOfDependents))))
test2$NumberOfDependents <- ceiling(rnorm(20,.73,1.08))
test2$NumberOfDependents <- ifelse(test2$NumberOfDependents < 0,0,test2$NumberOfDependents)
test1$NumberOfDependents <- as.numeric(as.character(test1$NumberOfDependents))
test3 <- rbind(test1,test2)
RFDF.holdout<-test3
RFDF.holdout$Target <- RFDF.holdout$SeriousDlqin2yrs
RFDF.holdout <- RFDF.holdout[,-c(1,2)]

sum(RFDF.dev$Target) / nrow(RFDF.dev)
sum(RFDF.holdout$Target) / nrow(RFDF.holdout)
```

# Fitting model
```{r}
tRF <-naiveBayes(as.factor(Target) ~ ., data = RFDF.dev)
summary(tRF)
tRF
```
## Scoring
```{r}
RFDF.dev$predict.class <- predict(tRF, RFDF.dev, type="class")
RFDF.dev$predict.score <- predict(tRF, RFDF.dev, type="raw")
head(RFDF.dev)
```

## deciling code
```{r}
decile <- function(x){
  deciles <- vector(length=10)
  for (i in seq(0.1,1,.1)){
    deciles[i*10] <- quantile(x, i, na.rm=T)
  }
  return (
    ifelse(x<deciles[1], 1,
           ifelse(x<deciles[2], 2,
                  ifelse(x<deciles[3], 3,
                         ifelse(x<deciles[4], 4,
                                ifelse(x<deciles[5], 5,
                                       ifelse(x<deciles[6], 6,
                                              ifelse(x<deciles[7], 7,
                                                     ifelse(x<deciles[8], 8,
                                                            ifelse(x<deciles[9], 9, 10
                                                            ))))))))))
}
```
## deciling
```{r}
RFDF.dev$deciles <- decile(RFDF.dev$predict.score[,2])
```

## Ranking code
```{r}
tmp_DT = data.table(RFDF.dev)
rank <- tmp_DT[, list(
  cnt = length(Target), 
  cnt_resp = sum(Target), 
  cnt_non_resp = sum(Target == 0)) , 
  by=deciles][order(-deciles)]
rank$rrate <- round(rank$cnt_resp * 100 / rank$cnt,2);
rank$cum_resp <- cumsum(rank$cnt_resp)
rank$cum_non_resp <- cumsum(rank$cnt_non_resp)
rank$cum_rel_resp <- round(rank$cum_resp / sum(rank$cnt_resp),2);
rank$cum_rel_non_resp <- round(rank$cum_non_resp / sum(rank$cnt_non_resp),2);
rank$ks <- abs(rank$cum_rel_resp - rank$cum_rel_non_resp);
rank
```

## Model Performance
```{r}
pred <- prediction(RFDF.dev$predict.score[,2], RFDF.dev$Target)
perf <- performance(pred, "tpr", "fpr")
plot(perf)
KS <- max(attr(perf, 'y.values')[[1]]-attr(perf, 'x.values')[[1]])
auc <- performance(pred,"auc"); 
auc <- as.numeric(auc@y.values)
gini = ineq(RFDF.dev$predict.score[,2], type="Gini")
auc
KS
gini
```
#confusion matrix for development
```{r}
with(RFDF.dev, table(Target, predict.class))
```

## Scoring of holdout data
```{r}
RFDF.holdout$predict.class <- predict(tRF, RFDF.holdout, type="class")
RFDF.holdout$predict.score <- predict(tRF, RFDF.holdout, type="raw")
with(RFDF.holdout, table(Target, predict.class))

RFDF.holdout$deciles <- decile(RFDF.holdout$predict.score[,2])
tmp_DT = data.table(RFDF.holdout)
h_rank <- tmp_DT[, list(
  cnt = length(Target), 
  cnt_resp = sum(Target), 
  cnt_non_resp = sum(Target == 0)) , 
  by=deciles][order(-deciles)]
h_rank$rrate <- round(h_rank$cnt_resp * 100 / h_rank$cnt,2);
h_rank$cum_resp <- cumsum(h_rank$cnt_resp)
h_rank$cum_non_resp <- cumsum(h_rank$cnt_non_resp)
h_rank$cum_rel_resp <- round(h_rank$cum_resp / sum(h_rank$cnt_resp),2);
h_rank$cum_rel_non_resp <- round(h_rank$cum_non_resp / sum(h_rank$cnt_non_resp),2);
h_rank$ks <- abs(h_rank$cum_rel_resp - h_rank$cum_rel_non_resp);
h_rank
```
#confusion matrix for holdout
```{r}
with(RFDF.holdout, table(Target, predict.class))
```
